dist: xenial

services:
  - docker
before_install:
  - docker pull mysql:5.7
  - docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7
  - docker pull epiclabs/docker-oracle-xe-11g
  - docker run --name oracle -d -p 127.0.0.1:1521:1521 -e ORACLE_ALLOW_REMOTE=true -v ${PWD}:/data epiclabs/docker-oracle-xe-11g
  # - docker inspect oracle
  # - docker ps -a
  - echo "Wait to allow Oracle to be initialized"
  - travis_wait sleep 10
  - docker top oracle
  - docker exec -it mysql mysqladmin ping -uroot -proot --wait=30 --silent
  - docker exec -it mysql mysql -u root -p'root' -s -e "create database id;create table id.worker_id(id bigint auto_increment primary key,created datetime default current_timestamp,ip varchar(60),hostname varchar(60),pid int,reason varchar(60),biz varchar(60))engine=innodb default charset=utf8mb4;create table id.t_seq ( name        varchar(60) primary key comment '序列名称，不用的序列，请使用不用的名字', start       bigint   default 0     not null comment 'SEQ 起始值，用于重新循环', seq         bigint   default 0     not null comment '当前的SEQ取值', step        int      default 10 not null comment '步长', water_level int      default 5  not null comment '低于多少水位线需要补充', cycle       tinyint  default 0     not null comment '是否允许循环，必须max_seq同时设置时才生效', max_seq     bigint   default 0     not null comment '允许最大的序列值，0 时不校验', created     datetime default current_timestamp comment '创建时间', updated     datetime on update current_timestamp comment '更新时间' ) engine = innodb default charset = utf8mb4 comment '序列取号表';"
  - docker exec -it oracle /bin/bash /data/scripts/wait-for-oracle.sh

language: java
install: mvn install -DskipTests -Dgpg.skip
jdk: openjdk8
sudo: false
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: bingoohuang-github
    token:
      secure: Q0b81ebLGrl8/lhQVwnPz+yOWMYqsI3QK4PjwPT8GPmbA47cs8oHiZDTm40mAb5lUvd1jkcMhmnG35ywIKoQswnkvCJdSYfSdmajXVALKB5I6sVSILec3TtZVfzahIScXi3C0wvUg8X0av9bj7L5qqi76sxGfAeSw/qp9/HCHtnB/H/98LIoCqf5pfqaSfGQP0i7JRq99U/9hFSdQ4cXJi7P1OD3LTcvfCL83XGSVoWydh8eSVDqRzsV7zZEPPpE7MNoMCgwot3SJashK7zYaMIU+9ML1mW31ncujHkF+zIBEELtU9aaymhPZSqeAqtTT+JCBdq8tgEx3Ikt2dWs38iq9bSaIP3bLMRpfEEh1ylBo6+eo8Oq3aVnfzWvdYfehcEKftUj3ePSBbO+CMWFddWOeFd7GWCBSE4RDE2tsvyBdefbsH0Nm5fy4U7HgEWMvzVz5FQTUIFvxgW67gL9U/HFBlPQfH1+oVV3+sbCpxv/jbAHiqMkB7UKNV6i+2mTpQH180JTO36J3fvKOKHPhRmvZ+AmbT5ehXrlb9qk7xZvEsXK5JogXYRX5bYB5Vqd+IJLFx5BFxkZoftgH2wz9ZpwBi090lOJrPq+sjW8qCpBS/lqvap4Y6ZoeQLg7sjmTIqLb4CN4EGlf39Z0YREfyXLxlcnbmajOhgly+X4hhE=
script:
  - mvn clean test jacoco:report coveralls:report install sonar:sonar -Dgpg.skip -Dsonar.organization=bingoohuang-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a7fe683637d6e1f54e194817cc36e78936d4fe61
