version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: 'dbs-mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    ports:
      - "3306:3306"
    volumes:
      - ./init/:/init/
    command: --default-authentication-plugin=mysql_native_password
  oracle:
    image: epiclabs/docker-oracle-xe-11g
    container_name: 'dbs-oracle11g'
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
    volumes:
      - ./init/:/init/
  postgres:
    image: postgres:12.3
    container_name: 'dbs-postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - ./init/:/init/
